server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true   #以IP地址注册到服务中心，相互注册使用IP地址
    instance-id: cloud-client-80  #eurrka服务列表超链接处名称
  client:
    service-url:    #指定服务注册中心的位置
      defaultZone: http://eureka6868.com:6868/eureka/,http://eureka6869.com:6869/eureka/,http://eureka6870.com:6870/eureka/

spring:
  application:
    name: cloud-client

app:
  service-url: http://CLOUD-SERVER

feign:
  hystrix:
    enabled: true   #开启Hystrix熔断器

info:
  app.name: cloud-study
  company.name: www.sunzhongwei.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: hystrix.stream