server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true   #以IP地址注册到服务中心，相互注册使用IP地址
    instance-id: cloud-client-8082  #eurrka服务列表超链接处名称
  client:
    service-url:    #指定服务注册中心的位置
      defaultZone: http://127.0.0.1:6868/eureka/

spring:
  application:
    name: com.ww-client

app:
  service-url: http://WW-SERVER/

feign:
  hystrix:
    enabled: true   #开启Hystrix熔断器

info:
  app.name: cloud-study
  company.name: www.sunzhongwei.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

