server:
  port: 6870
eureka:
  instance:
    hostname: eureka6870.com #eureka服务端的实例名称
  client:
    register-with-eureka: false     #是否向服务注册中心注册自己
    fetch-registry: false   #是否从Eureka中获取注册信息
    service-url:    #指定服务注册中心的位置
      defaultZone: http://eureka6868.com:6868/eureka/,http://eureka6869.com:6869/eureka/